### ISSUE TITLE
Query/Request: declare a function as async

### ISSUE THREAD

**Issue by xtheshumanator** [stephenh/ts-poet#2]
The current list of Modifiers does not have a way to declare a fucntion as async. Is it possible to add this?

https://github.com/stephenh/ts-poet/blob/master/src/Modifier.ts

Thanks.

**Comment by stephenh** [comment]
Yep, fixed in 0.6.0. Thanks!

**Comment by xtheshumanator** [comment]
Awesome, thank you!
