### ISSUE TITLE
Custom import aliases are not supported

### ISSUE THREAD

**Issue by YeeJone** [stephenh/ts-poet#24]
Like：  
`import { XXX as CustomizedXXX } from 'packages/override-properties/XXXX';`

**Comment by stephenh** [comment]
Ah yeah, that seems worth supporting...

I was thinking `imp("XXX:CustomizedXXX@packages/override-properties/XXX")` would be a good syntax for that.

Technically the `:` operator is already "taken" by the `t:` prefix I added for type-only imports...

But we could probably support both, and just still use `:` i.e.

```
imp("t:XXX:CustomizedXXX@packages/override-properties/XXX")
```

Would be:

```
import type { XXX as CustomizedXXX } from 'packages/override-properties/XXXX';
```

Open to better suggestions than the `:` separator.

If you'd like to submit a PR, that'd be great. Thanks!
