### ISSUE TITLE
Cannot import SymbolSpec

### ISSUE THREAD

**Issue by nao50** [stephenh/ts-poet#3]
Thank you for the wonderful library.
I have one question.

**Problems**
I cannot import SymbolSpec as follows:

```typescript
import { SymbolSpec } from 'ts-poet';
```

**Question**
SymbolSpecs could be imported, but could you tell me the way of writing that can achieve the function equivalent to `SymbolSpec.from()` via SymbolSpecs?

Or should I change [ts-poet/src/index.ts](https://github.com/stephenh/ts-poet/blob/a41f639fca5598e37ba6a6cdd8bd57de6a50d7b6/src/index.ts#L11) like TypeNames as follows?

```typescript
export * from './SymbolSpecs';
```

Thanks.

**Comment by stephenh** [comment]
> Thank you for the wonderful library.

Thanks!

> I cannot import SymbolSpec as follows:

Ah yeah, that is odd.

> export * from './SymbolSpecs';

Yeah, I think that'd be a good fix.

Looking at it a little bit, I'm also wondering if maybe the two `SymbolSpec` and `SymbolSpecs` classes should be merged. The fact that they are separate is kind of a hold-over from one of the "*-poet" libraries I ported this from, and I think their idea was that `SymbolSpecs` had all of the static factory functions for each `SymbolSpec` subclass.

But I don't know if this is a necessary distinction.

So, anyway, if you'd like to submit a PR that combines the two `SymbolSpec` and `SymbolSpecs` types into just a single `SymbolSpec`, I think that'd be cool, but also just a simple PR to export both of them from `index.ts` for now is great too.

Thanks!

**Comment by stephenh** [comment]
`SymbolSpec` has since been renamed to `Import`.
