### ISSUE TITLE
README Example doesn't generate expected code.

### ISSUE THREAD

**Issue by ws-gregm** [stephenh/ts-poet#53]
```
@ws-gregm ➜ (staging) $ ts-node src/bin/gen


export class Greeter {

  private name: string;

  constructor(private name: string) {
  }

  
  greet(): <string> {
    return .from(`Hello $name`);
  }

}
```

Should see ```Observable.from(`Hello $name`);```, However, Observable doesn't appear as per the example.

**Comment by stephenh** [comment]
Ah yeah, the readme example comes from a really old precursor to ts-poet, so used an out-dated `imp` syntax; I've updated it to use:

```
const Observable = imp("Observable@rxjs");
```

And you should see it work. See the "Import Specs" section for other valid import specs.

Thanks for the report!

**Comment by ws-gregm** [comment]
Perfect! Thank you so much.
